### ISSUE TITLE
Compiler dependency?

### ISSUE THREAD

**Issue by suaefar** [hayamdk/ryzen_segv_test#2]
Context: Ryzen 1700 (stock settings) Ubuntu 17.04 with mainline kernel 4.12 lowlatency.

Compiled with gcc 6.3.0 this program results in crashes (mostly segfaults) every minute or so.
With gcc 7.0.1 (from ppa:ubuntu-toolchain-r/test), however, it ran 2 hours without any error.

Is this also a compiler issue?

**Comment by hayamdk** [comment]
I also see that frequency of segfaults is dependent to compiler significantly.
But I can't say that this is compiler issue(bug).
When I check generated binary code by gcc6.3, there is no suspicious instructions.

But rather I think that this code hits specific instruction/data pattern when this is compiled by gcc6.3.
When I change variable definition position or execution flow slightly, this code doesn't cause any error even if compiled by gcc6.3.

**Comment by suaefar** [comment]
Thank you, that sounds reasonable. It seems that with other versions than gcc 6.3 it is much less efficient. You might add a hint in the instructions.
